def on_forever():
    R = maqueen.read_patrol(maqueen.Patrol.PATROL_RIGHT)
    L = maqueen.read_patrol(maqueen.Patrol.PATROL_LEFT)
    D = maqueen.ultrasonic(PingUnit.CENTIMETERS)
    if D<=5 :
        maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 0)
        maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 0)
        music.play_tone(Note.G, music.beat(100))
        basic.pause(20)
        music.play_tone(Note.G, music.beat(1000))
        music.rest(music.beat(5000))
        R = maqueen.read_patrol(maqueen.Patrol.PATROL_RIGHT)
        L = maqueen.read_patrol(maqueen.Patrol.PATROL_LEFT)
        D = maqueen.ultrasonic(PingUnit.CENTIMETERS)
    else :
        if L==0 and R==0 : 
            maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 67)
            maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 50)
            R = maqueen.read_patrol(maqueen.Patrol.PATROL_RIGHT)
            L = maqueen.read_patrol(maqueen.Patrol.PATROL_LEFT)
            D = maqueen.ultrasonic(PingUnit.CENTIMETERS)
        elif L==0 and R==1 :
            maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CCW, 60)
            maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 52)
            basic.pause(100)
            maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 50)
            maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 37)
            R = maqueen.read_patrol(maqueen.Patrol.PATROL_RIGHT)
            L = maqueen.read_patrol(maqueen.Patrol.PATROL_LEFT)
            D = maqueen.ultrasonic(PingUnit.CENTIMETERS)
        elif L==1 and R==0 :
            maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 60)
            maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CCW, 52)
            basic.pause(100)
            maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 50)
            maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 37)
            R = maqueen.read_patrol(maqueen.Patrol.PATROL_RIGHT)
            L = maqueen.read_patrol(maqueen.Patrol.PATROL_LEFT)
            D = maqueen.ultrasonic(PingUnit.CENTIMETERS)
        else :
            maqueen.motor_run(maqueen.Motors.M1, maqueen.Dir.CW, 0)
            maqueen.motor_run(maqueen.Motors.M2, maqueen.Dir.CW, 0)
            R = maqueen.read_patrol(maqueen.Patrol.PATROL_RIGHT)
            L = maqueen.read_patrol(maqueen.Patrol.PATROL_LEFT)
            D = maqueen.ultrasonic(PingUnit.CENTIMETERS)
basic.forever(on_forever)
def on_forever2():
    maqueen.write_led(maqueen.LED.LED_LEFT, maqueen.LEDswitch.TURN_ON)
    maqueen.write_led(maqueen.LED.LED_RIGHT, maqueen.LEDswitch.TURN_OFF)
    basic.pause(250)
    maqueen.write_led(maqueen.LED.LED_LEFT, maqueen.LEDswitch.TURN_OFF)
    maqueen.write_led(maqueen.LED.LED_RIGHT, maqueen.LEDswitch.TURN_ON)
    basic.pause(250)
basic.forever(on_forever2)